config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles
  resources :searches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_full_text, against: {
    title: 'A',
    content: 'B'
  }

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/search.rb
class Search < ApplicationRecord
  validates :term, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :ip, presence: true, uniqueness: true

  has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= find_or_create_user_by_ip
  end

  private

  def find_or_create_user_by_ip
    user_ip = request.remote_ip
    Rails.cache.fetch("user_#{user_ip}", expires_in: 1.day) do
      User.find_or_create_by(ip: user_ip)
    end
  end
end

app/controllers/articles_controller.rb
# rubocop:disable all

class ArticlesController < ApplicationController
  before_action :set_user_ip, only: [:index]
  before_action :initialize_search_stack, only: [:index]
  before_action :update_search_stack, only: [:index]

  SEARCH_STACK_EXPIRY = 20.seconds

  def index
    term = params[:term]

    if term.present?
      current_user.save
      @articles = Article.search_full_text(term)
    else
      @articles = Article.all
    end

    respond_to do |format|
      format.html do
        if turbo_frame_request?
          render partial: 'articles', locals: { articles: @articles, searches: @searches }
        else
          render :index
        end
      end

      format.turbo_stream do
        turbo_stream.append('articles', partial: 'articles', locals: { articles: @articles, searches: @searches })
      end
    end
  end

  private

  def set_user_ip
    @user = User.find_or_initialize_by(ip: request.remote_ip)
    @user.save unless @user.persisted?
  end

  def initialize_search_stack
    session[:search_stack] ||= []
  end

  def update_search_stack
    term = params[:term]
    stack = session[:search_stack]

    if term.present?
      entry = stack.find { |e| e[:complete_term] == term }
      if entry.present?
        entry[:count] ||= 0
        entry[:count] += 1
      else
        stack.push({ fragments: term.split, complete_term: term, timestamp: Time.now, count: 1 })
      end
    end

    stack.reject! do |entry|
      entry.nil? || entry[:timestamp].nil? || entry[:timestamp] < (Time.now - SEARCH_STACK_EXPIRY)
    end
    session[:search_stack] = stack
    @searches = stack.sort_by do |search_entry|
                  search_entry[:timestamp]
                end.reverse.map { |result_entry| { term: entry[:complete_term], count: result_entry[:count] } }
  end
end
# rubocop:enable all

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/articles/_article.html.erb
<div class="article">
  <p><%= link_to article.title, article_path(article) %></p>
</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag 'articles' do %>
  <%= render articles %>
<% end %>

app/views/articles/index.html.erb
<h1>Welcome to our Article Database</h1>

<h2>What article are you looking for?</h2>

<%= form_with(url: articles_path, method: :get, data: { controller: "search-form", turbo_frame: "articles", turbo_action: "advance" }) do |form| %>
  <%= form.text_field :term, placeholder: "Search articles...", data: { action: "input->search-form#search" } %>
  <%= form.submit "Search" %>
<% end %>

<h2>Searches History:</h2>
<%= render 'searches/searches', searches: @searches %>

<h2>Articles:</h2>
<%= render 'articles', articles: @articles %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealTimeTrendSeeker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/_searches.html.erb
<%= turbo_frame_tag 'searches-history' do %>
  <% if @searches.present? %>
    <ul id="searches-history">
      <% @searches.each do |search| %>
        <p><%= "#{search[:term]} (#{search[:count]} times)" %></p>
      <% end %>
    </ul>
  <% else %>
    <p>There are no searches yet.</p>
  <% end %>
<% end %>